### ISSUE TITLE
Clonen des GitLab repos funktioniert bei mir nicht

### ISSUE THREAD

**Issue by lr101** [owaldhorst-hka/bslab-warmup#1]
Bei mir funktioniert der Befehl: 

git clone https://iz-gitlab-01.hs-karlsruhe.de/waol0001/bslab-warmup

aufgrund eines Timeout fehlers nicht. Ist das Repo noch zugägnglich?

**Comment by owaldhorst-hka** [comment]
Ihr Befehl klont das Repository vom gitlab-Server der Fakultät, der nur aus dem Hochschulnetz bzw. per VPN erreichbar ist. Wenn Sie von GitHub klonen wollen, ist der Befehl:

git clone https://github.com/owaldhorst-hka/bslab-warmup.git
